### ISSUE TITLE
lower case (local) marks not displayed

### ISSUE THREAD

**Issue by Konfekt** [mattn/ctrlp-mark#3]
Add a mark `a` to the buffer by `ma`. Then `marks` shows `a`, but `CtrlPMarks` does not over here.

**Comment by ratheesh** [comment]
Commenting Line 45 of autoload/ctrlp/mark.vim fixes this issue. I was able to verify.

@mattn If this fix is fine, I can raise a pull request. Please confirm.

**Comment by mattn** [comment]
please do

**Comment by mattn** [comment]
Closed by https://github.com/mattn/ctrlp-mark/pull/4
