### ISSUE TITLE
Error E700 with vim-fugitive

### ISSUE THREAD

**Issue by srustamo** [mattn/ctrlp-mark#5]
When [vim-fugitive](https://github.com/tpope/vim-fugitive) is installed, calling `CtrlPMark` and selecting a mark for file under git control (or opening vim without a file in a non git controlled dir)  causes E700.

See [screencast](https://asciinema.org/a/vARY8tigoVCN24RdPZsbu3d8p) for details. 

Edit: opening the same mark with `'` vim stock command does not casue the error, all things being equal.

**Comment by mattn** [comment]
What happen with `g'a` ? (a is register you marked)

**Comment by srustamo** [comment]
The mark is `A`, both `'A` and `g'A` work without errors.

**Comment by mattn** [comment]
I installed fugitive but not reproduced.

**Comment by srustamo** [comment]
Make sure to open vim in a nongit dir, and then try CtrlPMark.

It looks like the problem of autoloaded fugitive. Opening vim in a nongit
pwd doesn't trigger fugitive autoload.

**Comment by srustamo** [comment]
I was using an older version of vim-fugtive. Updated to the latest, no issues.
